export const VOTE_TODO = 'VOTE_TODO' //投票
export const SEARCH_LIST = 'SEARCH_LIST' // 查询
export const SET_VOTELIST = 'SET_VOTELIST' //设置投票列表
export const GET_VOTELIST = 'GET_VOTELIST' //设置投票列表
export const TRAGGER_SCROOL_FLAG = 'TRAGGER_SCROOL_FLAG' //改变上拉下拉状态
export const LISTLOADING = 'LISTLOADING' //存储loading状态
export const TOUCH_BOTTOM_FLAG = 'TOUCH_BOTTOM_FLAG' //存储是否触底的判断
export const INITIALVOTELIST = 'INITIALVOTELIST'  //初始化投票列表数据
export const RESETSCROLLFLAG = 'RESETSCROLLFLAG'  //重置上拉下拉状态
export const GET_VOTELIST_ID = 'GET_VOTELIST_ID'  // 获取指定id下的数据
export const SETUPLOADIMG  = 'SETUPLOADIMG'       // 存储图片上传
export const GETUPLOADIMG  =  'GETUPLOADIMG'	  // 获取存储图片
export const REMOVEUPLOADIMG = 'REMOVEUPLOADIMG'  //移除存储图片